name: Regex Hub PPT
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@main
        env:
          BRANCH: master
          FOLDER: docs/dist
          BUILD_SCRIPT: cd docs && npm install && npm run build
